In [1]:
import pandas as pd

Create a Pandas Series from a list.

In [2]:
data = [2,5,3,5,45,1,28,48]

data = pd.Series(data)
data

0     2
1     5
2     3
3     5
4    45
5     1
6    28
7    48
dtype: int64

Create a Series with custom indexes.

In [3]:
import numpy as np
data = [2,5,3,5,45,1,28,48]

data = pd.Series(data, index=list(range(5,13)))
data

5      2
6      5
7      3
8      5
9     45
10     1
11    28
12    48
dtype: int64

In [4]:
data = {
    "Name": ["Rahul", "Komal", "Ramesh"],
    "Age": [25, 23, 28],
    "Score": [10, 7, 8]
}

df = pd.DataFrame(data)
df

     Name  Age  Score
0   Rahul   25     10
1   Komal   23      7
2  Ramesh   28      8

Create a DataFrame from a list of dictionaries.

In [5]:
data = [
    {"Name": "Rahul", "Age": 25, "Score": 10},
    {"Name": "Komal", "Age": 23, "Score": 7},
    {"Name": "Ramesh", "Age": 28, "Score": 8}
]

df = pd.DataFrame(data)

In [6]:
df

     Name  Age  Score
0   Rahul   25     10
1   Komal   23      7
2  Ramesh   28      8

Create a student information DataFrame.

In [7]:
data = {
    "Name" : ['Rahul', 'Bhanu', 'Satyam'],
    "Roll No" : ['001', '002', '003'],
    "Branch" : ['CSE', 'cicil', np.nan]
   }


df = pd.DataFrame(data)
df

     Name Roll No Branch
0   Rahul     001    CSE
1   Bhanu     002  cicil
2  Satyam     003    NaN

Display the first 5 rows.

In [8]:
df = pd.read_csv("mushrooms.csv")
df.head(5)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

Display the last 10 rows.

In [9]:
df.head(10)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
5,e,x,y,y,t,a,f,c,b,n,...,s,w,w,p,w,o,p,k,n,g
6,e,b,s,w,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,n,m
7,e,b,y,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,s,m
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
9,e,b,s,y,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,s,m

Find DataFrame shape.

In [10]:
df.shape

(8124, 23)

Find column names.

In [11]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

Find data types.

In [12]:
df.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

Generate descriptive statistics.

In [13]:
df.describe()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

Select one column.

In [14]:
print(df['class'])

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: object

Select multiple columns.

In [15]:
print(df[['class', 'cap-shape']])

     class cap-shape
0        p         x
1        e         x
2        e         b
3        p         x
4        e         x
...    ...       ...
8119     e         k
8120     e         x
8121     e         f
8122     p         k
8123     e         x

[8124 rows x 2 columns]

Select rows using loc.

loc selectd column by using there name

In [16]:
print(df.loc[:5, ['class']])

  class
0     p
1     e
2     e
3     p
4     e
5     e

Select rows using iloc.

iloc used slicing for selecting the columns

In [17]:
print(df.iloc[:, :2])

     class cap-shape
0        p         x
1        e         x
2        e         b
3        p         x
4        e         x
...    ...       ...
8119     e         k
8120     e         x
8121     e         f
8122     p         k
8123     e         x

[8124 rows x 2 columns]

In [18]:
filtered_df = df[df['class'] == 'p']
filtered_df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8114,p,f,y,c,f,m,a,c,b,y,...,y,c,c,p,w,n,n,w,c,d
8116,p,k,y,n,f,s,f,c,n,b,...,k,p,w,p,w,o,e,w,v,l
8117,p,k,s,e,f,y,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8118,p,k,y,n,f,f,f,c,n,b,...,s,p,w,p,w,o,e,w,v,d
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l

Select employees older than 25.

In [19]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam"],
    "Age": [25, 22, 28],
    "Score": [85, 65, 92]
}

d_f = pd.DataFrame(data)

In [20]:
print(d_f[d_f['Age'] > 22])

     Name  Age  Score
0   Rahul   25     85
2  Satyam   28     92

Select employees earning above ₹50,000.

In [21]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam"],
    "Age": [25, 22, 28],
    "Salary" : [70000,12000,25000,]
}

d_f = pd.DataFrame(data)

In [22]:
print(d_f[d_f['Salary'] > 50000])

    Name  Age  Salary
0  Rahul   25   70000

Filter using multiple conditions.

In [26]:
print(d_f[(d_f['Salary'] > 50000) & (d_f['Age'] > 22)] )

    Name  Age  Salary
0  Rahul   25   70000

Filter using isin().

In [27]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit"],
    "Branch": ["CSE", "Civil", "CSE", "ECE"]
}

d_f = pd.DataFrame(data)
d_f

     Name Branch
0   Rahul    CSE
1   Bhanu  Civil
2  Satyam    CSE
3    Amit    ECE

In [30]:
print(d_f[d_f['Branch'].isin(['CSE', 'ECE'])])

     Name Branch
0   Rahul    CSE
2  Satyam    CSE
3    Amit    ECE

Detect missing values.

In [31]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit"],
    "Branch": ["CSE", np.nan, "CSE", np.nan]
}

d_f = pd.DataFrame(data)
d_f

     Name Branch
0   Rahul    CSE
1   Bhanu    NaN
2  Satyam    CSE
3    Amit    NaN

In [34]:
d_f.isna()

    Name  Branch
0  False   False
1  False    True
2  False   False
3  False    True

Count missing values by column.

In [35]:
d_f.isna().sum()

Name      0
Branch    2
dtype: int64

Drop rows containing missing values.

In [38]:
print(d_f.dropna())

     Name Branch
0   Rahul    CSE
2  Satyam    CSE

Drop columns containing missing values.

In [39]:
print(d_f.dropna(axis=1))

     Name
0   Rahul
1   Bhanu
2  Satyam
3    Amit

Fill numeric missing values with mean.

In [40]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "kunal"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}

df = pd.DataFrame(data)

In [41]:
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam   NaN
3    Amit  32.0
4  Keshav  36.0
5   Raman   NaN
6   kunal  25.0

In [46]:
mean = np.mean(df['Age'])
print(mean)

28.0

In [47]:
df.fillna(mean)

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam  28.0
3    Amit  32.0
4  Keshav  36.0
5   Raman  28.0
6   kunal  25.0

Fill missing values with median.

In [48]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "kunal"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}

df = pd.DataFrame(data)
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam   NaN
3    Amit  32.0
4  Keshav  36.0
5   Raman   NaN
6   kunal  25.0

In [53]:
series = pd.Series(df['Age'])
median = series.median()
median

np.float64(25.0)

In [54]:
df.fillna(median)

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam  25.0
3    Amit  32.0
4  Keshav  36.0
5   Raman  25.0
6   kunal  25.0

Fill categorical missing values with mode.

In [55]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "kunal"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}

df = pd.DataFrame(data)
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam   NaN
3    Amit  32.0
4  Keshav  36.0
5   Raman   NaN
6   kunal  25.0

In [56]:
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam  25.0
3    Amit  32.0
4  Keshav  36.0
5   Raman  25.0
6   kunal  25.0

Forward-fill missing values.

In [57]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "kunal"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}

df = pd.DataFrame(data)
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam   NaN
3    Amit  32.0
4  Keshav  36.0
5   Raman   NaN
6   kunal  25.0

In [59]:
df['Age'] = df['Age'].ffill()
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam  22.0
3    Amit  32.0
4  Keshav  36.0
5   Raman  36.0
6   kunal  25.0

Backward-fill missing values.

In [60]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "kunal"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}

df = pd.DataFrame(data)
df

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam   NaN
3    Amit  32.0
4  Keshav  36.0
5   Raman   NaN
6   kunal  25.0

In [61]:
df['Age'] = df['Age'].backfill()
df

C:\Users\Phibonacci\AppData\Local\Temp\ipykernel_12892\2059927365.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df['Age'] = df['Age'].backfill()

     Name   Age
0   Rahul  25.0
1   Bhanu  22.0
2  Satyam  32.0
3    Amit  32.0
4  Keshav  36.0
5   Raman  25.0
6   kunal  25.0

Detect duplicate rows.

In [62]:
data = {
    "Name": ["Rahul", "Bhanu", "Satyam", "Amit", "Keshav", "Raman", "Rahul"],
    "Age": [25, 22, np.nan, 32,36, np.nan, 25]
}
df = pd.DataFrame(data)

In [64]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

Remove duplicate rows.